name: audit
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ "frontend", "backend" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Audit (${{ matrix.dir }})
        run: |
          set -e
          cd ${{ matrix.dir }}
          # Create lockfile if missing so 'npm ci' works
          if [ ! -f package-lock.json ]; then
            npm i --package-lock-only
          fi
          npm ci
          npm audit --omit=dev --audit-level=high
